version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug
  - Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan --version
  - git submodule update --init --recursive

before_build:
  - md build
  - cd build
  - conan install ..
  - cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=RapidjsonJSONAdapterStandalone

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\RapidJSONAdapter.sln

artifacts:
  - path: 'build\src\RapidJSONAdapter\$(configuration)\RapidJSONAdapter.lib'
    name: RapidJSONAdapter.lib
