version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan --version

before_build:
  - md build
  - cd build
  - conan install ..
  - cmake .. -G "Visual Studio 15 2017 Win64"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\RapidJSONAdapter.sln

after_build:
  - conan export-pkg ../conanfile.py RapidJSONAdapter/0.1@systelab/testing
  - conan test ../test_package/conanfile.py RapidJSONAdapter/0.1@systelab/testing -s build_type={configuration}

test_script:
  - ps: cd bin
  - RapidJSONAdapterTest.exe --gtest_output=xml:RapidJSONAdapterTest.xml

after_test:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\RapidJSONAdapterTest.xml))

artifacts:
  - path: 'build\lib\RapidJSONAdapter.lib'
    name: RapidJSONAdapter.lib
