version: '1.0.{build}'

image: Visual Studio 2017

init:
  - ps: >- 
      if($env:appveyor_repo_tag -eq 'True') {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      } else {
        Update-AppveyorBuild -Version "1.0.$($env:APPVEYOR_BUILD_NUMBER)"
      }

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

before_build:
  - md build
  - cd build
  - conan install ..
  - cmake .. -G "Visual Studio 15 2017 Win64"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\RapidJSONAdapter.sln

after_build:
  - conan export-pkg ../conanfile.py RapidJSONAdapter/%APPVEYOR_BUILD_VERSION%@systelab/testing -s build_type=%CONFIGURATION%
  - conan test ../test_package/conanfile.py RapidJSONAdapter/%APPVEYOR_BUILD_VERSION%@systelab/testing -s build_type=%CONFIGURATION%

test_script:
  - ps: cd bin
  - RapidJSONAdapterTest.exe --gtest_output=xml:RapidJSONAdapterTest.xml

after_test:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\RapidJSONAdapterTest.xml))

artifacts:
  - path: 'build\lib\RapidJSONAdapter.lib'
    name: RapidJSONAdapter.lib

deploy_script:
  - if($env:appveyor_repo_tag -eq 'True') {
      conan upload RapidJSONAdapter/%APPVEYOR_BUILD_VERSION%@systelab/testing --all -r systelab-bintray
    } else {
      echo "Not uploading because this is not a tag build"
    }

